"""phase 2 metrics tables

Revision ID: 168d9152ae2e
Revises: e1125a27a78f
Create Date: 2026-09-25 09:48:36.291278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168d9152ae2e'
down_revision: Union[str, Sequence[str], None] = 'e1125a27a78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'trade_date', name='uq_index_price_per_day')
    )
    op.create_index('ix_index_prices_index_date', 'index_prices', ['index_id', 'trade_date'], unique=False)
    op.create_table('momentum_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('calc_version', sa.String(length=32), nullable=False),
    sa.Column('return_1m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('return_3m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('return_6m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('return_12m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of', 'calc_version', name='uq_momentum_snapshot')
    )
    op.create_table('relative_strength_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('benchmark', sa.String(length=64), nullable=False),
    sa.Column('calc_version', sa.String(length=32), nullable=False),
    sa.Column('rs_1m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rs_3m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rs_6m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rs_12m', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rs_trend', sa.Enum('IMPROVING', 'STABLE', 'DETERIORATING', name='rstrend', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of', 'benchmark', 'calc_version', name='uq_relative_strength_snapshot')
    )
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('calc_version', sa.String(length=32), nullable=False),
    sa.Column('sma20', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sma50', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sma100', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sma200', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ema20', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ema50', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ema200', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('roc10', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stoch_k', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stoch_d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('williams_r', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cci20', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('adx14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('plus_di14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('minus_di14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('atr14', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('hist_vol_20', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('hist_vol_60', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('bollinger_upper', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bollinger_middle', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bollinger_lower', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bollinger_width', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('bollinger_percent_b', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume_sma20', sa.BigInteger(), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume_spike', sa.Boolean(), nullable=False),
    sa.Column('obv', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low_52w', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('dist_from_high_52w_pct', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('dist_from_low_52w_pct', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('drawdown_pct', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('recovery_pct', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('breakout_52w', sa.Boolean(), nullable=False),
    sa.Column('breakdown_52w', sa.Boolean(), nullable=False),
    sa.Column('trend_state', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of', 'calc_version', name='uq_tech_snapshot')
    )
    op.create_index('ix_technical_instrument_asof', 'technical_indicators', ['instrument_id', 'as_of'], unique=False)
    op.create_table('valuation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('calc_version', sa.String(length=32), nullable=False),
    sa.Column('pe', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('pb', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('peg', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fcf_yield', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pe_median_3y', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('pe_percentile_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_deviation_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pb_percentile_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ev_ebitda_percentile_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('valuation_label', sa.Enum('CHEAP', 'FAIRLY_VALUED', 'MODERATELY_EXPENSIVE', 'EXPENSIVE', name='valuationlabel', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of', 'calc_version', name='uq_valuation_snapshot')
    )
    op.add_column('income_statements', sa.Column('shares_outstanding', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_statements', 'shares_outstanding')
    op.drop_table('valuation_metrics')
    op.drop_index('ix_technical_instrument_asof', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_table('relative_strength_metrics')
    op.drop_table('momentum_metrics')
    op.drop_index('ix_index_prices_index_date', table_name='index_prices')
    op.drop_table('index_prices')
    # ### end Alembic commands ###
