"""initial schema

Revision ID: e1125a27a78f
Revises: 
Create Date: 2026-09-24 18:13:03.802202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1125a27a78f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('industry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Enum('QUARTERLY', 'ANNUAL', 'HALF_YEARLY', name='periodtype', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fiscal_year', sa.String(length=16), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_worth', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_end', 'period_type', 'source', name='uq_balance_sheet_period')
    )
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Enum('QUARTERLY', 'ANNUAL', 'HALF_YEARLY', name='periodtype', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fiscal_year', sa.String(length=16), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('investing_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('financing_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_end', 'period_type', 'source', name='uq_cash_flow_period')
    )
    op.create_table('fundamental_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'metric', 'as_of', name='uq_fundamental_metric_snapshot')
    )
    op.create_table('income_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Enum('QUARTERLY', 'ANNUAL', 'HALF_YEARLY', name='periodtype', native_enum=False), nullable=False),
    sa.Column('fiscal_year', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda_margin_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_margin_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_end', 'period_type', 'source', name='uq_income_statement_period')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchange', native_enum=False), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('instrument_type', sa.Enum('EQ', 'INDEX', name='instrumenttype', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_instrument_exchange_symbol')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('SPLIT', 'BONUS', 'DIVIDEND', 'RIGHTS', 'MERGER', 'DEMERGER', 'OTHER', name='corporateactiontype', native_enum=False), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('ratio_numerator', sa.BigInteger(), nullable=True),
    sa.Column('ratio_denominator', sa.BigInteger(), nullable=True),
    sa.Column('dividend_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_identifier', sa.String(length=128), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'action_type', 'ex_date', 'source', name='uq_corporate_action_identity')
    )
    op.create_index('ix_corporate_actions_instrument_ex', 'corporate_actions', ['instrument_id', 'ex_date'], unique=False)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('adjustment_factor', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('is_incomplete', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'trade_date', name='uq_daily_price_per_day')
    )
    op.create_index('ix_daily_prices_instrument_date', 'daily_prices', ['instrument_id', 'trade_date'], unique=False)
    op.create_table('index_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_defunct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['indices.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'instrument_id', 'effective_from', name='uq_membership_interval')
    )
    op.create_index('ix_membership_lookup', 'index_memberships', ['instrument_id', 'effective_from'], unique=False)
    op.create_table('ingestion_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', name='severity', native_enum=False), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_errors')
    op.drop_index('ix_membership_lookup', table_name='index_memberships')
    op.drop_table('index_memberships')
    op.drop_index('ix_daily_prices_instrument_date', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index('ix_corporate_actions_instrument_ex', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_table('instruments')
    op.drop_table('income_statements')
    op.drop_table('fundamental_metrics')
    op.drop_table('cash_flows')
    op.drop_table('balance_sheets')
    op.drop_table('companies')
    op.drop_table('industries')
    op.drop_table('sectors')
    op.drop_table('ingestion_runs')
    op.drop_table('indices')
    # ### end Alembic commands ###
